### PR TITLE
updated for usage in actix-web 4.0.0-beta.21

### PR DESCRIPTION
**Pull request by 1zun4secondary**
Hello,

I am very happy about this library. It works great and is so much easier to use than handling the multipart data yourself.
I ran into issues with using actix-web 4.0.0 because of the tokio runtime and the FromRequest trait changes. I forked your library and somehow fixed it. I literally ruined your code, but might consider fixing it up and merging it into another branch for other people to use. 👍🏼 

Greetings,
1zuna

### CODE REVIEW

**Comment by jacob-pro** [comment]
Hey, thanks @1zun4 I'm glad it is useful to you.
Yeah I would be happy to accept a PR to upgrade master to actix-4 (and I will just make a branch for the actix-3 version).
Would you be willing to tidy up this PR a bit first - I will add a few comments for what needs to be done?

**Comment by 1zun4secondary** [comment]
> Hey, thanks @1zun4 I'm glad it is useful to you. Yeah I would be happy to accept a PR to upgrade master to actix-4 (and I will just make a branch for the actix-3 version). Would you be willing to tidy up this PR a bit first - I will add a few comments for what needs to be done?

I am not very familiar with writing tests using actix-web 4.0.0. I've been looking into it, but it seems there are a few things missing for multipart support. What has to be done is following:

- [ ] Rewrite/Update tests for actix-web 4.0.0 (2x) and run all of them and pass
- [x] Handle async block errors and pass IO errors
- [x] Remove some of commented out code (which is not required anymore)

**Comment by jacob-pro** [comment]
@1zun4 
I have upgraded this to actix 4 in this commit 
https://github.com/jacob-pro/actix-easy-multipart/commit/d97232296d4be938042aec96a983157e5cc153af
https://crates.io/crates/actix-easy-multipart/2.0.0-beta.1

To fix the tests I migrated to using `reqwest` instead of `awc` and `actix-multipart-rfc7578` because the two were causing version conflicts with all the different beta versions of actix crates in the tree.

**Comment by 1zun4secondary** [comment]
Good 👍🏼

**Pull request closed without merging**
